title: "GHPF Lab"
description: "Greenhouse Horticulture and Plant Factory Lab â€” Seoul National University"

url: "https://evergreendasol.github.io"
baseurl: "/Trial-2-lab-web"

author: "Tae In Ahn"
email: "tiahn@snu.ac.kr"
timezone: "Asia/Seoul"
lang: "en"

markdown: kramdown

plugins:
  - jekyll-sitemap
